Protokoll von ffki-treffen-2016-10-06 importieren
freifunk-kiel/ffki-blog pull request #13
Opened 2016-11-03 20:37 UTC by fsteinel

2016-11-03 22:59 UTC, rubo77 requested changes

2016-11-03 22:59 UTC, rubo77 commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
> +     - Der Freifunk am Vinetaplat
Z fehlt

2016-11-03 22:59 UTC, rubo77 commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
> +     Die neue Funktion (Knotenalarm)http://ffki.de/nodealarm.html für Betreiber von Freifunk Knoten st nun auf Startseite aktivierbar.
Leerzeichen

2016-11-05 21:48 UTC, fsteinel commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
> +     Die neue Funktion (Knotenalarm)http://ffki.de/nodealarm.html für Betreiber von Freifunk Knoten st nun auf Startseite aktivierbar.
Ich kann da nur raten, meintest du mehr Leerzeichen vor den Zeilen?

2016-11-05 21:48 UTC, fsteinel commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
> +     - Der Freifunk am Vinetaplat
Habe ich eingepflegt.

2016-11-06 22:45 UTC, rubo77 commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
> +      Die neue Funktion [Knotenalarm](http://ffki.de/nodealarm.html) für Betreiber von Freifunk Knoten st nun auf Startseite aktivierbar.
i bei ist fehlt

2016-11-06 22:45 UTC, rubo77 commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
>        Interressierte Knotenbetreiber können sich dort eintragen um be Ausfällen benachrichtigt zu werden
i bei "bei" fehlt.

Am besten eine Rechtschreibprüfung benutzen

2016-11-13 11:05 UTC, fsteinel commented on _posts/2016-10-06-freifunk-treffen-protokoll.md
>        Interressierte Knotenbetreiber können sich dort eintragen um be Ausfällen benachrichtigt zu werden
ich habe die Rechtschreibung sowie die fehlenden Buchstaben hinzugefügt

2016-12-20 00:06 UTC, merged