Protokoll Januar ergänzt
freifunk-kiel/ffki-blog pull request #42
Opened 2019-01-03 19:52 UTC by eNBeWe

2019-01-03 20:10 UTC, rubo77 requested changes

2019-01-03 20:10 UTC, rubo77 commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Diverse Leute waren auf dem 36c3 in Leipzig.
35

2019-01-03 20:10 UTC, rubo77 commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Es wurde uns ein Peering zum Freifunk Rheinland zukommen lassen. Wir könnten also in nächster Zeit ein eigenes AS einrichten.
Grammatik

2019-01-03 20:10 UTC, rubo77 commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +
...?

2019-01-03 20:10 UTC, rubo77 commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Der Offene Netze Nord e.V. ist (noch) nicht gemeinnützig und primär dafür da, dass die Dachstandorte rechtssicher betrieben werden können.
Noch kann beim onn weg

2019-01-06 17:57 UTC, eNBeWe commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Diverse Leute waren auf dem 36c3 in Leipzig.
Mist, du hast es gesehen ... ;)

2019-01-06 17:57 UTC, eNBeWe commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Es wurde uns ein Peering zum Freifunk Rheinland zukommen lassen. Wir könnten also in nächster Zeit ein eigenes AS einrichten.
Done

2019-01-06 17:57 UTC, eNBeWe commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +Der Offene Netze Nord e.V. ist (noch) nicht gemeinnützig und primär dafür da, dass die Dachstandorte rechtssicher betrieben werden können.
Done

2019-01-06 17:58 UTC, eNBeWe commented on _posts/2019-01-03-Freifunk-Treffen-Protokoll.md
> +
Hups, da ist mir wohl ein Satzteil abhanden gekommen ... done

2019-01-07 18:26 UTC, merged